name: core_mvc
author: thetrompf, resem.pl <bkc@resem.pl>
description: MVC framework inspired by ASP.NET MVC now known as CoreMVC
version: 0.1.1
license: BSD
homepage: https://github.com/thetrompf/dart-core-mvc
dev_dependencies:
  test: any
  mockito: any
